# Generated by Django 5.0.3 on 2024-04-19 13:46

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
