# Generated by Django 5.0.3 on 2024-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('U', 'Undecided'), ('M', 'Male'), ('F', 'Female'), ('H', 'Attack Helicopter')], default='U', max_length=3, verbose_name='gender'),
        ),
    ]
