# Generated by Django 5.0.3 on 2024-03-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('trip', '0004_remove_trip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='travel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trip.trip', verbose_name='Images'),
        ),
    ]
