# Generated by Django 5.0.3 on 2024-04-19 15:24

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
