# Generated by Django 5.0.3 on 2024-03-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
