# Generated by Django 5.0.3 on 2024-04-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='Date')),
                ('title_photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Title_photo')),
                ('content', models.TextField(blank=True, verbose_name='Description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('published', models.BooleanField(verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='categories.category', verbose_name='Categories')),
                ('tag', models.ManyToManyField(blank=True, related_name='tags', to='tags.tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
    ]
