# Generated by Django 5.0.3 on 2024-04-19 14:57

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
