# Generated by Django 5.0.3 on 2024-03-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_date_alter_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
    ]
