# Generated by Django 5.0.3 on 2024-05-17 08:26

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/', verbose_name='title_photo'),
        ),
    ]
